<?php

/**
 * @file
 * Icon Filter module
 */

/**
 * Implements hook_filter_info().
 */
function icon_filter_filter_info() {
  $filters['filter_icon'] = array(
    'title' => t('Convert [icon:%iconname%] tags'),
    'process callback' => '_icon_filter_icon',
    'tips callback' => '_icon_filter_icon_tips',
  );

  return $filters;
}

/**
 * Implements callback_filter_process().
 *
 * Converts icons like [icon:pencil] to their equivalent svg. Can also add
 * classes: [icon:pencil class=icon-3x,icon-rotate-45] or styles
 * [icon:pencil style="color: red;"]
 */
function _icon_filter_icon($text, $filter, $format, $langcode, $cache, $cache_id) {
  backdrop_theme_initialize();

  $icons = array();
  if (preg_match_all('/\[icon(\:(.+))?( .+)?\]/isU', $text, $matches, PREG_SET_ORDER)) {
    foreach ($matches as $match) {
      if (!isset($icons[$match[0]])) {
        $attributes = array();

        if ($match[3] && preg_match_all('/\s+([a-zA-Z]+)\=([0-9a-zA-Z";,:\-_]+)(\s+)?([a-zA-Z]+)?(\=)?([0-9a-zA-Z";:\-_]+)?/i', $match[3], $matches_attributes, PREG_SET_ORDER)) {
          if (isset($matches_attributes[0][1]) && isset($matches_attributes[0][2])) {
            $attributes[$matches_attributes[0][1]] = $matches_attributes[0][2];
          }
          if (isset($matches_attributes[0][4]) && isset($matches_attributes[0][6])) {
            $attributes[$matches_attributes[0][4]] = $matches_attributes[0][6];
          }
        }
        if (isset($attributes['class'])) {
          $attributes['class'] = explode(',', $attributes['class']);
          if (!is_array($attributes['class'])) {
            $attributes['class'] = array($attributes['class']);
          }
        }
        $attributes['class'][] = 'icon-filter';

        if (isset($attributes['style'])) {
          $attributes['style'] = trim($attributes['style'], '"');
        }

        $icons[$match[0]] = icon($match[2], array('attributes' => $attributes));
      }
    }
  }
  foreach ($icons as $search => $replace) {
    if (!empty($replace)) {
      $text = str_replace($search, $replace, $text);
    }
  }

  return $text;
}


/**
 * Implements callback_filter_tips().
 *
 * Provides help for the icon filter.
 *
 * @see filter_filter_info()
 */
function _icon_filter_icon_tips($filter, $format, $long = FALSE) {
  $help = t('Convert <code>[icon:icon-name]</code> to inline svg. Can add classes and styles, e.g.: <code>[icon:pencil class=icon-2x,icon-rotate-45 style="color: red;"]</code>. Multiple classes are separated by commas. Available classes include relative sizing: <code>icon-2xs</code>, <code>icon-xs</code>, <code>icon-sm</code>, <code>icon-lg</code>, <code>icon-xl</code>, <code>icon-2xl</code>; literal sizing: <code>icon-1x</code> to <code>icon-10x</code>; flip: <code>icon-flip-horizontal</code>, <code>icon-flip-vertical</code>; and rotate: <code>icon-rotate-45</code>, <code>icon-rotate-90</code>, <code>icon-rotate-135</code>, <code>icon-rotate-180</code>, <code>icon-rotate-225</code>.');
  $icon_browser = '';
  if (module_exists('icon_browser')) {
    $icon_browser = t(' <a href="@url">Browse available icons</a>.', array('@url' => '/admin/config/media/icons/browse'));
  }
  if ($long) {
    return $help . $icon_browser;
  }
  else {
    return $help . $icon_browser;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function icon_filter_preprocess_page(&$variables) {
  backdrop_add_css(backdrop_get_path('module', 'icon_filter') . '/css/icon_filter.css');
}
